### Coin change problem

In [21]:
import numpy as np
x=int(input("Please input the number you want:"))
n=int(input("Please input the total number of coin:"))
List=[]
for i in range(n):
    print("Please input No.",i+1,"money in descending order")
    money=int(input())
    List.append(money)
coin=np.zeros(len(List),dtype=np.int_)
index=0
while(x>0):
    if(x>=List[index]):
        coin[index]+=1
        x-=List[index]
    else:
        index+=1
for i in range(len(List)):
    if(coin[i]!=0):
        print(List[i],"for",coin[i],end=",") 

Please input the number you want:86
Please input the total number of coin6
Please input No. 1 money in descending order
100
Please input No. 2 money in descending order
50
Please input No. 3 money in descending order
25
Please input No. 4 money in descending order
10
Please input No. 5 money in descending order
5
Please input No. 6 money in descending order
1
50 for 1,25 for 1,10 for 1,1 for 1,

### Most common sequence 

In [1]:
import numpy as np
def common_sequence(array,max_str,min_str):
    i=array.shape[0]-2
    j=array.shape[1]-2
    while(i>=0):
        c_j=j
        while(c_j>=0):
            if(min_str[i]==max_str[c_j]):
                cost=0
            else:
                cost=1
            array[i][c_j]=min(array[i+1][c_j+1]+cost,array[i+1][c_j]+2,array[i][c_j+1]+2)
            c_j-=1
        i-=1
    
str1=input("Please input string 1:")
str2=input("Please input string 2:")
if(len(str1)>len(str2)):
    max_str=str1
    min_str=str2
else:
    max_str=str2
    min_str=str1
array1=np.zeros((len(min_str)+1,len(max_str)+1),dtype=np.int_)
last1=len(array1[len(min_str)])-1
last2=len(min_str)
while(last1>0):
    array1[len(min_str),last1-1]=array1[len(min_str),last1]+2 ###when last==-1,it means it will go back to the last element!!
    last1-=1
while(last2>0):
    array1[last2-1,len(max_str)]=array1[last2,len(max_str)]+2
    last2-=1
common_sequence(array1,max_str,min_str)
print(array1)

Please input string 1:abcd123
Please input string 2:123abcd
[[ 7  8  8  6  8 10 12 14]
 [ 8  6  7  8  6  8 10 12]
 [ 9  7  5  6  7  6  8 10]
 [10  8  6  4  5  6  6  8]
 [ 8  9  7  5  3  4  5  6]
 [10  8  8  6  4  2  3  4]
 [12 10  8  7  5  3  1  2]
 [14 12 10  8  6  4  2  0]]
