## Dynamic Programming 
#### Most calories mapping
#### Bottom up approach

In [22]:
import numpy as np
def matrix(i,j):
    ma=np.zeros((i,j))
    for x in range(i):
        for y in range(j):
            print("Please input the",x,y,"element")
            ma[x,y]=int(input())
    return ma
def dyna_programming(ma,i,j):###This is the route about person 1, using Bottom up approach 
    move_left=j ###This is opposite to the right 
    move_up=i ### This is opposite to the bottom
    if(move_left==0 and move_up==0):
        return ma[0,0]
    elif(move_left==0):
        bt=0
        while(i>=0):
            bt+=ma[i,0]
            i-=1
        return bt
    elif(move_up==0):
        rt=0
        while(j>=0):
            rt+=ma[0,j]
            j-=1
        return rt
    else:
        return max((ma[i,j]+dyna_programming(ma,i-1,j)),(ma[i,j]+dyna_programming(ma,i,j-1)))
i=int(input("Please input the row"))
j=int(input("Please input the column"))
ma=matrix(i,j)
print(ma)
print(dyna_programming(ma,i-1,j-1))

Please input the row3
Please input the column3
Please input the 0 0 element
12
Please input the 0 1 element
2
Please input the 0 2 element
3
Please input the 1 0 element
4
Please input the 1 1 element
5
Please input the 1 2 element
6
Please input the 2 0 element
1
Please input the 2 1 element
7
Please input the 2 2 element
8
[[12.  2.  3.]
 [ 4.  5.  6.]
 [ 1.  7.  8.]]
36.0


In [25]:
help(input)

Help on method raw_input in module ipykernel.kernelbase:

raw_input(prompt='') method of ipykernel.ipkernel.IPythonKernel instance
    Forward raw_input to frontends
    
    Raises
    ------
    StdinNotImplentedError if active frontend doesn't support stdin.

