## Dynamic Programming 

#### (i) Construction of Algorithm
##### matrix:This method is to create a matrix that user can input all calories elements.
<i>In this method,there are two parameters:i and j, i is the number of row and j is the number of column.I create an all zeros matrix by using numpy and then I could input each element in this matrix. Finally return this matrix.</i>  
##### p1_dyna_calories: This method is to calculate the maximum calories that Person 1 burnt.
<i>Using bottom to up approach</i>
* 1.Three parameters:ma(calories matrix),i(<b>steps of moving up</b>),j(<b>steps of moving left</b>)
* 2.Because the person 1 should be back to (0,0) from (p-1,q-1),so we should move left q-1 steps and move up p-1 steps
* 3.Then,we should determine whether the total calories cost of moving left is bigger than moving up.If moving up, stpes of up will reduce by 1,same as moving left.So this method should using recursive thinking, which is return max(ma[i,j]+p1_dyna_calories(ma,i-1,j)<b>(Moving up)</b>,ma[i,j]+p1_dyna_calories(ma,i,j-1)<b>(Moving left)</b>)
* 4.If i==0,which means person 1 is in the first row,so person 1 cannot move up,the last thing is to move left,so we calculate the sum of last left elements to find the calories;If j==0,which means person 1 is in the first column,so person 1 cannot move left,the last thing is to move up,same as i==0;
* 5.If i==0 and j==0 at the same time,meaning person 1 is in the (0,0).

##### p2_dyna_calories: This method is to calculate the maximum calories that Person 2 burnt.
<i>Using bottom to up approach(Different from p1_dyna_calories)</i>
* 1.Five parameters:ma(calories matrix),i(<b>Position of row(i)</b>),j(<b>Position of column(j)</b>),mvLeft(<b>steps of moving left</b>),mvDown(<b>steps of moving dowm</b>)
* 2.Because Person 2 is moving to (p-1,0) from (0,q-1),which is different from Person 1.The position of Person 1 (i,j) can be considered that there are i steps to moving up and j steps to moving left.But according to Person,we should record the steps and postion at the same time. Also,moving down will make i+1 and steps-1.
* 3.Same thinking as p1_dyna_calories, return the max(ma[i,j]+p2_dyna_calories(ma,i+1,j,mvLeft,mvDown-1)<b>(Moving down,i+1 and mvDown-1)</b>,ma[i,j]+p2_dyna_calories(ma,i,j-1,mvLeft-1,mvDown)<b>(Moving left,j-1 and mvLeft-1)</b>).Comparing this steps and find the maximum calories.

In [31]:
import numpy as np
import timeit as ti
def matrix(i,j):
    ma=np.zeros((i,j))
    for x in range(i):
        for y in range(j):
            print("Please input the",x*(i+1)+y,"element")
            ma[x,y]=int(input())
    return ma
def p1_dyna_calories(ma,i,j):###This is the route about person 1, using Bottom up approach 
    move_up=i ### This is opposite to the bottom
    move_left=j ###This is opposite to the right 
    if(move_left==0 and move_up==0):
        return ma[0,0]
    elif(move_left==0):
        bt=0
        while(i>=0):
            bt+=ma[i,0]
            i-=1
        return bt
    elif(move_up==0):
        rt=0
        while(j>=0):
            rt+=ma[0,j]
            j-=1
        return rt
    else:
        return max((ma[i,j]+p1_dyna_programming(ma,i-1,j)),(ma[i,j]+p1_dyna_programming(ma,i,j-1)))
def p2_dyna_calories(ma,i,j,mvLeft,mvDown):
    if(mvLeft==0 and mvDown==0):
        return ma[i,0]
    elif(mvLeft==0):
        calories=0
        while(mvDown>=0):
            calories+=ma[i,0]
            i+=1
            mvDown-=1
        return calories
    elif(mvDown==0):
        calories=0
        while(mvLeft>=0):
            calories+=ma[i,mvLeft]
            mvLeft-=1
        return calories
    else:
        return max((ma[i,j]+p2_dyna_calories(ma,i,j-1,mvLeft-1,mvDown)),(ma[i,j]+p2_dyna_calories(ma,i+1,j,mvLeft,mvDown-1)))


#### (ii)Analysis of Algorithm


#### (iii)Scenario 
* 1.Input i and j
* 2.Time consuming

In [35]:
i=int(input("Please input the row"))
j=int(input("Please input the column"))
ma=matrix(i,j)
print(ma)

start=ti.default_timer()
cal1=p1_dyna_calories(ma,i-1,j-1)
end=ti.default_timer()

print("The time costs by algorithm person 1 is %fs"%(end-start))
print("The maximum calories of Person 1 is %d"%cal1)
start=ti.default_timer()
cal2=p2_dyna_calories(ma,0,j-1,j-1,i-1)
end=ti.default_timer()
print("The time costs by person 2 is %fs"%(end-start))
print("The maximum calories of Person 2 is %d"%cal2)


Please input the row3
Please input the column3
Please input the 0 element
1
Please input the 1 element
2
Please input the 2 element
3
Please input the 4 element
4
Please input the 5 element
5
Please input the 6 element
6
Please input the 8 element
7
Please input the 9 element
8
Please input the 10 element
9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
The time costs by algorithm person 1 is 0.000119s
The maximum calories of Person 1 is 29
The time costs by person 2 is 0.000117s
The maximum calories of Person 2 is 33
