In [82]:
import numpy as np
def split_four(matrix):
    row=matrix.shape[0]
    col=matrix.shape[1]
    return matrix[:row//2,:col//2],matrix[:row//2,col//2:],matrix[row//2:,:col//2],matrix[row//2:,col//2:]
def strassen(A,B):
    row1=A.shape[0]
    col1=A.shape[1]
    row2=B.shape[0]
    col2=B.shape[1]
    if(row1==1 and col1==1 and row2==1 and col2==1):
        return A*B
    else:
        a11,a12,a21,a22=split_four(A)
        b11,b12,b21,b22=split_four(B)
        m1=strassen(a11+a22,b11+b22)
        m2=strassen(a21+a22,b11)
        m3=strassen(a11,b12-b22)
        m4=strassen(a22,b21-b11)
        m5=strassen(a11+a12,b22)
        m6=strassen(a21-a11,b11+b12)
        m7=strassen(a12-a22,b21+b22)
        c11=m1+m4-m5+m7
        c12=m3+m5
        c21=m2+m4
        c22=m1+m3-m2+m6
        c1=np.hstack((c11,c12))
        c2=np.hstack((c21,c22))
        c=np.vstack((c1,c2))
        return c
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b=np.array([[17,18,19,20],[21,22,23,24],[25,26,27,28],[29,30,31,32]])

print(a)
l='-'*50
print(l)
print(b)
print(l)
c=strassen(a,b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------------------------------------
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
--------------------------------------------------
[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]
